---
- name: Validate OpenShift connectivity
  hosts: localhost

  tasks:
    - name: Create a k8s namespace
      redhat.openshift.k8s:
        api_version: v1
        name: demo
        kind: namespace
        state: present
